name: üöÄ Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows you to run this manually from the Actions tab

env:
  AZURE_FUNCTIONAPP_NAME: 'func-databricks-demo-znpacs' # Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './published'        
  DOTNET_VERSION: '8.0.x' 
  PROJECT_PATH: './src/DataOrchestrator'                              

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'üìÇ Debug - List Files'
      run: ls -R src/

    - name: 'üß™ Run Unit Tests'
      shell: bash
      run: |
        pushd ${{ env.PROJECT_PATH }}
        dotnet test
        popd

    - name: 'üèóÔ∏è Build and Publish'
      shell: bash
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        zip -r ../functionapp.zip .

    - name: 'üîê Log in to Azure'
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: 'üöÄ Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './functionapp.zip'